server:
  port: ${PORT:8099}

spring:
  application:
    name: spark
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# CORS 설정 (환경변수로 오버라이드 가능)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3001,http://localhost:3002,http://localhost:5173}