-- 플레이스홀더 리워드 데이터 (추가 예정)
DELETE FROM rewards;

INSERT INTO rewards (
    id, title, description, category, brand, original_price, required_points, 
    discount_percentage, image_url, expiration_days, is_active, is_popular, 
    is_premium, exchange_count, total_exchanged, created_at, updated_at
) VALUES 
(
    'placeholder_01', 
    '카페 상품 추가 예정', 
    '다양한 카페 브랜드 상품이 곧 추가됩니다', 
    'COFFEE', 
    '추가 예정', 
    '미정',
    99999, 
    0, 
    'https://images.unsplash.com/photo-1549185545-f5b8a1fc481a?w=400', 
    30, 
    true, 
    false, 
    false, 
    0, 
    0, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
),
(
    'placeholder_02', 
    '쇼핑 상품 추가 예정', 
    '인기 쇼핑몰 상품권이 곧 추가됩니다', 
    'SHOPPING', 
    '추가 예정', 
    '미정',
    99999, 
    0, 
    'https://images.unsplash.com/photo-1570197506759-8b9de9b7a1b3?w=400', 
    90, 
    true, 
    false, 
    false, 
    0, 
    0, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
),
(
    'placeholder_03', 
    '엔터테인먼트 상품 추가 예정', 
    '영화, 공연 등 다양한 엔터테인먼트 상품이 곧 추가됩니다', 
    'ENTERTAINMENT', 
    '추가 예정', 
    '미정',
    99999, 
    0, 
    'https://images.unsplash.com/photo-1489599743715-0a6c9f46b9e0?w=400', 
    60, 
    true, 
    false, 
    false, 
    0, 
    0, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
),
(
    'placeholder_04', 
    '음식 상품 추가 예정', 
    '맛있는 음식점 상품권이 곧 추가됩니다', 
    'FOOD', 
    '추가 예정', 
    '미정',
    99999, 
    0, 
    'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400', 
    14, 
    true, 
    false, 
    false, 
    0, 
    0, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
),
(
    'placeholder_05', 
    '뷰티 상품 추가 예정', 
    '뷰티 브랜드 상품이 곧 추가됩니다', 
    'BEAUTY', 
    '추가 예정', 
    '미정',
    99999, 
    0, 
    'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400', 
    365, 
    true, 
    false, 
    false, 
    0, 
    0, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
),
(
    'placeholder_06', 
    '프리미엄 상품 추가 예정', 
    'SPARK 프리미엄 혜택이 곧 추가됩니다', 
    'PREMIUM', 
    'SPARK', 
    '미정',
    99999, 
    0, 
    'https://images.unsplash.com/photo-1584515501397-335d595b2a17?w=400', 
    365, 
    true, 
    false, 
    true, 
    0, 
    0, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    brand = EXCLUDED.brand,
    original_price = EXCLUDED.original_price,
    required_points = EXCLUDED.required_points,
    discount_percentage = EXCLUDED.discount_percentage,
    image_url = EXCLUDED.image_url,
    expiration_days = EXCLUDED.expiration_days,
    is_active = EXCLUDED.is_active,
    is_popular = EXCLUDED.is_popular,
    is_premium = EXCLUDED.is_premium,
    updated_at = CURRENT_TIMESTAMP;