-- 테스트 스토리 데이터 생성
INSERT INTO stories (
    id, user_id, mission_id, mission_title, mission_category, story_text, 
    images, location, auto_tags, user_tags, is_public, likes_count, like_count,
    comments_count, hash_tags, created_at, updated_at
) VALUES 
(
    'story_001', 
    'user_01', 
    'tpl_adv_001', 
    '새로운 동네 탐험하기', 
    'ADVENTURE', 
    '회사 근처에 숨겨진 작은 카페를 발견했어요! 직접 로스팅하는 원두 향이 정말 좋았고, 사장님이 친절하게 원두에 대해 설명해주셨어요 ☕️ 다음에 또 가고 싶은 곳이네요!',
    'https://images.unsplash.com/photo-1549185545-f5b8a1fc481a?w=400',
    '강남구',
    '카페,새로운경험,맛있음',
    '콜드브루,스타벅스',
    true,
    24,
    24,
    7,
    '#콜드브루 #첫경험 #맛있어요',
    NOW() - INTERVAL '2 hours',
    NOW()
),
(
    'story_002', 
    '2190d61c-379d-4452-b4da-655bf67b4b71', 
    'tpl_soc_001', 
    '카페에서 낯선 사람과 대화하기', 
    'SOCIAL', 
    '한강에서 혼자 프리스비 던지고 있었는데, 지나가던 분들이 같이 하자고 하시더라고요! 새로운 친구들도 만나고 너무 재미있었어요 🥏 역시 용기를 내보길 잘했네요!',
    'https://images.unsplash.com/photo-1584515501397-335d595b2a17?w=400',
    '한강공원',
    '산책,석양,여유,자연',
    '한강,석양',
    true,
    31,
    31,
    12,
    '#한강공원 #석양 #산책',
    NOW() - INTERVAL '4 hours',
    NOW()
),
(
    'story_003', 
    'user_01', 
    'tpl_hlt_001', 
    '15분 산책하기', 
    'HEALTH', 
    '엘리베이터 대신 계단으로! 처음엔 힘들었지만 10층까지 올라가니 뿌듯하고 개운하네요 💪 운동 안 한 지 오래됐는데 이런 식으로라도 몸을 움직이니 좋은 것 같아요.',
    'https://images.unsplash.com/photo-1597644568217-780bd0b0efb2?w=400',
    '회사',
    '운동,건강,계단,성취감',
    '건강,운동',
    true,
    18,
    18,
    5,
    '#건강 #운동 #계단챌린지',
    NOW() - INTERVAL '6 hours',
    NOW()
),
(
    'story_004', 
    '2190d61c-379d-4452-b4da-655bf67b4b71', 
    'tpl_cre_001', 
    '오늘의 하늘 그리기', 
    'CREATIVE', 
    '오늘 하늘이 정말 예뻤어서 그림으로 그려봤어요! 실력은 부족하지만 그리는 과정이 너무 힐링되더라구요 🎨 앞으로도 계속 그려보고 싶어요.',
    'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400',
    '집',
    '그림,창작,힐링,예술',
    '그림,하늘,예술',
    true,
    15,
    15,
    3,
    '#그림 #창작 #힐링',
    NOW() - INTERVAL '8 hours',
    NOW()
),
(
    'story_005', 
    'user_01', 
    'tpl_lea_001', 
    '새로운 단어 5개 배우기', 
    'LEARNING', 
    '오늘 영어 단어 5개를 새로 배웠어요! Serendipity라는 단어가 특히 인상깊었습니다. "뜻밖의 발견"이라는 뜻인데, 오늘 이 미션을 통해 새로운 단어들을 발견한 것 자체가 serendipity네요! 📚',
    'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    '도서관',
    '학습,영어,단어,성장',
    '영어,공부,단어',
    true,
    22,
    22,
    8,
    '#영어공부 #단어암기 #성장',
    NOW() - INTERVAL '10 hours',
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    story_text = EXCLUDED.story_text,
    likes_count = EXCLUDED.likes_count,
    like_count = EXCLUDED.like_count,
    comments_count = EXCLUDED.comments_count,
    updated_at = NOW();